[tool.pytest.ini_options]
addopts = "-v -ra --cov=app --cov-report=term-missing"
testpaths = [
    "tests"
]

[tool.pytest_env]
DB_NAME = "python_be_syokyu_test"

[tool.ruff]
line-length = 200
select = ["ALL"]
# Assume Python 3.12
target-version = "py312"

[tool.ruff.lint]
preview = true
ignore = ["D100", "ANN201", "D103", "D101", "B008", "CPY001", "DOC201", "DOC501"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.per-file-ignores]
"tests/**/*.py" = [
    "S101",
    "ANN001",
    "ANN201",
    "N802",
    "ARG",
    "D100"
]
"__init__.py" = [
    "D104"
]